version: '3.7'
services:
  onlyoffice-documentserver:
    image: onlyoffice/documentserver:latest
    container_name: nexio-documentserver
    restart: always
    ports:
      - "8082:80"              # Espone l'editor su http://localhost:8082
    environment:
      - JWT_ENABLED=false      # TEMPORANEAMENTE disabilitato per debug
      - JWT_SECRET=nexio-secret-key-2025-onlyoffice-jwt-secure-token     # chiave sincronizzata con PHP
      - JWT_HEADER=Authorization
    volumes:
      - ./data:/var/www/onlyoffice/Data      # salvataggio dati
      - ./logs:/var/log/onlyoffice           # log del server
      - ../documents/onlyoffice:/var/www/onlyoffice/documents  # NUOVO: accesso diretto ai file DOCX
    extra_hosts:
      - "host.docker.internal:host-gateway"    # Assicura che host.docker.internal funzioni
    networks:
      - onlyoffice-net

  # Nginx file server per servire i documenti a OnlyOffice
  nginx-fileserver:
    image: nginx:alpine
    container_name: nexio-fileserver
    restart: always
    ports:
      - "8083:8080"           # Espone il file server su http://localhost:8083
    volumes:
      - ../documents/onlyoffice:/var/www/onlyoffice/documents:ro  # Monta i documenti in read-only
      - ./nginx-config/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - onlyoffice-net

networks:
  onlyoffice-net:
    driver: bridge
