-- Creazione tabella documenti
CREATE TABLE IF NOT EXISTS `documenti` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `codice` varchar(50) UNIQUE NOT NULL,
  `titolo` varchar(255) NOT NULL,
  `descrizione` text,
  `contenuto` longtext,
  `file_path` varchar(500),
  `tipo_documento` varchar(50),
  `formato` varchar(10),
  `dimensione_file` bigint DEFAULT 0,
  `stato` enum('bozza','pubblicato','archiviato') DEFAULT 'bozza',
  `versione` int(11) DEFAULT 1,
  `azienda_id` int(11) NOT NULL,
  `cartella_id` int(11) DEFAULT NULL,
  `creato_da` int(11) NOT NULL,
  `data_creazione` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modificato_da` int(11) DEFAULT NULL,
  `data_modifica` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `classificazione_id` int(11) DEFAULT NULL,
  `template_id` int(11) DEFAULT NULL,
  `scadenza` date DEFAULT NULL,
  `tags` text,
  `metadata` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_codice` (`codice`),
  KEY `idx_azienda` (`azienda_id`),
  KEY `idx_cartella` (`cartella_id`),
  KEY `idx_creato_da` (`creato_da`),
  KEY `idx_stato` (`stato`),
  KEY `idx_tipo` (`tipo_documento`),
  KEY `idx_data_creazione` (`data_creazione`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;